{"uuid":"708af27a-dd94-4d8c-bf1c-2850f840ddd7","historyId":"5be87cecbeb9e9ad911a0b6ef746fb1f","fullName":"com.thetestingacademy.TestVWOLogin.TestInvalidLogin","labels":[{"name":"package","value":"com.thetestingacademy.TestVWOLogin"},{"name":"testClass","value":"com.thetestingacademy.TestVWOLogin"},{"name":"testMethod","value":"TestInvalidLogin"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"VWOLoginSeleniumAutomationTestNg"},{"name":"subSuite","value":"com.thetestingacademy.TestVWOLogin"},{"name":"host","value":"DESKTOP-CDMB554"},{"name":"thread","value":"5772@DESKTOP-CDMB554.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"blocker"}],"links":[],"name":"TestInvalidLogin","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [https://www.facebook.com/recover/initiate/?lara_product=www_first_password_failure] but found [https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&lwv=100]","trace":"java.lang.AssertionError: expected [https://www.facebook.com/recover/initiate/?lara_product=www_first_password_failure] but found [https://www.facebook.com/login/device-based/regular/login/?login_attempt=1&lwv=100]\r\n\tat org.testng.Assert.fail(Assert.java:111)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1578)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:150)\r\n\tat org.testng.Assert.assertEquals(Assert.java:132)\r\n\tat org.testng.Assert.assertEquals(Assert.java:656)\r\n\tat org.testng.Assert.assertEquals(Assert.java:666)\r\n\tat com.thetestingacademy.TestVWOLogin.TestInvalidLogin(TestVWOLogin.java:42)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)\r\n\tat org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)\r\n\tat org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)\r\n\tat org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)\r\n\tat org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)\r\n\tat org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:739)\r\n\tat org.testng.TestRunner.run(TestRunner.java:614)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:421)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:312)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1208)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1112)\r\n\tat org.testng.TestNG.run(TestNG.java:1079)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\n"},"stage":"finished","description":"TC#1-Verify that with invalid username and valid password, Login is not successful !!","steps":[],"attachments":[],"parameters":[],"start":1732082105078,"stop":1732082139730}